name: Release Obsidian plugin
permissions:
  contents: write

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build plugin
        run: npm run build

      - name: Create plugin ZIP
        run: |
          mkdir -p obsidian-line-ending-copyfix
          cp main.js manifest.json obsidian-line-ending-copyfix/
          zip -r obsidian-line-ending-copyfix.zip obsidian-line-ending-copyfix/

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${GITHUB_REF#refs/tags/}"

          gh release create "$tag" \
            --title="$tag" \
            obsidian-line-ending-copyfix.zip